### ISSUE TITLE
Provide 1D, 2D, 3D bindings as submodules of vampyr

### ISSUE THREAD

**Issue by robertodr** [MRChemSoft/vampyr#26]

**Comment by robertodr** [comment]
With @evelinbatt excellent work we're in a much better position to achieve this now. We can maybe have an hackaton soon?

**Comment by bjorgve** [comment]
sure, when? I can host :)

**Comment by evelinbatt** [comment]
I'm soo happy to hear that :):)

**Comment by robertodr** [comment]
> sure, when? I can host :)

Send a Slack message and we can take it from there?

**Comment by robertodr** [comment]
Closed with #32
