### ISSUE TITLE
cannot access dot product between two vectors in new vampyr

### ISSUE THREAD

**Issue by Gabrielgerez** [MRChemSoft/vampyr#76]
The dot product for two vectors containing `vp.FunctionTree` cannot be accessed through the new style of `vampyr`.
I've tried these two methods

1. ```
    vp.dot( [vp.FunctionTree, vp.FunctionTree, vp.FunctionTree], [vp.FunctionTree, vp.FunctionTree, vp.FunctionTree])
    ```
2. ```
    product_tree = vp.FunctionTree(MRA)
    vp.dot(product_tree, [vp.FunctionTree, vp.FunctionTree, vp.FunctionTree], [vp.FunctionTree, vp.FunctionTree, vp.FunctionTree])
    ```

**Comment by ilfreddy** [comment]
is that the right function to call? I thought dot would give a scalar out of two MW functions. In other words, the integral of the product.

**Comment by Gabrielgerez** [comment]
> is that the right function to call? I thought dot would give a scalar out of two MW functions. In other words, the integral of the product.

The classic dot  product is the sum of the product between the elements of two vectors. Both definitions should be correct. As far as I understand.

**Comment by stigrj** [comment]
yes, both should be possible
```
double <- FunctionTree . FunctionTree
FunctionTree <- FunctionTreeVector . FunctionTreeVector
```
but the latter has dropped out of our interface...
